package org.Assignment3.net;
import java.util.Scanner;

public class RealtimeEncapsualtion {

    private double id;
    private String name;

    public RealtimeEncapsualtion() {
        // Only Person class can access and assign
        id = Math.random();
        sayHello();
    }

    // This method is protected for giving access within Person class only
    private void sayHello() {
        System.out.println("Hello your ID is autogenerated here for security purpose, Thanks...... :" + getId());
    }

    public double getId() {
        return id;
    }

    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
}
 class EncapsualtionTest
{
    public static void main(String[] args)
    {
        Scanner sc = new Scanner(System.in);
        System.out.print("Enter your name : ");
        String name = sc.next();
        sc.close();
        
    	RealtimeEncapsualtion p1 = new RealtimeEncapsualtion();
        p1.setName(name);
        /*
         * Note: As id and name are encapsulated in Person class, those cannot be accessed 
         * directly here. Also there is no way to assign id in this
         * class. Try to uncomment below code and you would find compile time error.
         */
        // p1.id = "123";
        // p1.name = "this will give compile time error";
        // p1.sayHello(); // You can't access this method, as it is private to Person

        System.out.println("ID    : " + p1.getId()); 
        System.out.println("Name  : " + p1.getName());
    }
}